### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by jlsnow301** [EmeraldCityPromotions/iShootGlobal#1]
Our first page should feature infinite scroll through a collection of images.
These can be sourced anywhere at the moment.

**Comment by jaohara** [comment]
Thinking about this a bit now - 

- Should contain some component based on the [shadcn Card](https://ui.shadcn.com/docs/components/card) to hold the content
- Each content card will link to a more Entry-specific view (modal or page, I'm leaning towards modal) that displays content meta, a larger version of the content with the proper aspect ratio, and buttons to vote for the content
- Initial batch of content (images/video) could be requested via `getServerSideProps()` [(docs)](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props) on containing page and passed in as a prop 
- Content should be stored in state somewhere, initialized to a collection of the content passed as a prop - not sure if it should be owned by the `<InfiniteScroll>` component itself or in a more app-wide context
- Further content would be grabbed with `fetch()` and stored in state as well
- Loading could be triggered via the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
- For better UX, we might want to load more content than will fit on the viewport and anticipate a page load earlier to reduce the amount of empty cards
