### ISSUE TITLE
Build out Draft of Main View 

### ISSUE THREAD

**Issue by jaohara** [EmeraldCityPromotions/iShootGlobal#9]
We want to get a simple draft of the [Main View](https://excalidraw.com/#json=gLR34kpeXVCaicSwU2yME,DIyyM5FxmynjmmXurd-mKg) to get familiar with using [shadcn](https://ui.shadcn.com/docs) components.

- We're ignoring authorization for this basic draft and treating it as if the user is already logged in.
- The body of the page should contain an `<InfiniteScroll>` (#1) component that displays content of the selected type.
- There should be some sort of Switch or Toggle to change between Photo and Video content and have the feed reflect the change.
- Expanding upon the basic functionality, we should move on to having each content card click through to an Entry-specific view. 
- **A lot of the heavy lifting of this page will be done by the `<InfiniteScroll>` component,** but we can start blocking it out without it. We could even hard-code a "feed" (static list of elements) for early iterations.
- The page itself could load the initial feed content via `getServerSideProps()` ([docs](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props)) and pass it into the `<InfiniteScroll>` component

**Comment by jlsnow301** [comment]
getServersideProps would not apply here as we're using the app router
